set_property IOSTANDARD LVCMOS33 [get_ports {din[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {din[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {dout[0]}]

set_property PACKAGE_PIN P5 [get_ports {din[7]}]
set_property PACKAGE_PIN P4 [get_ports {din[6]}]
set_property PACKAGE_PIN P3 [get_ports {din[5]}]
set_property PACKAGE_PIN P2 [get_ports {din[4]}]
set_property PACKAGE_PIN M4 [get_ports {din[2]}]
set_property PACKAGE_PIN R2 [get_ports {din[3]}]
set_property PACKAGE_PIN N4 [get_ports {din[1]}]
set_property PACKAGE_PIN R1 [get_ports {din[0]}]
set_property PACKAGE_PIN J3 [get_ports {dout[2]}]
set_property PACKAGE_PIN J2 [get_ports {dout[1]}]
set_property PACKAGE_PIN K2 [get_ports {dout[0]}]

